apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-7zyq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-7zyq
    app.kubernetes.io/part-of: tkrw-pr712-0075-0047-app
  name: devfile-sample-7zyq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-7zyq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-7zyq
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0047-tenant/tkrw-pr712-0075-0047-app/devfile-sample-7zyq@sha256:e9310c2741a42212e6ef655bf47d86a83a2fa3c57da8626131a1196c219f1123
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
